version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
   install:
      - method: pip
        path: .
        extra_requirements:
           - docs
      - method: pip
        path: ..
sphinx:
   configuration: docs/conf.py

formats:
  - pdf
  - epub
